/// <reference types='cypress'/>

import { DesafioWebjumpElements } from "../elements/DesafioWebjump.elements";

export const DesafioWebjumpPages = {
    clicarNoBotaoCadastrar(){
        DesafioWebjumpElements.botaoCadastro().should('be.visible').click();
    },
    inserePrimeiroNome(primeiroNome){
        DesafioWebjumpElements.campoPrimeiroNome().should('be.visible').type(primeiroNome);
    },
    insereUltimoNome(ultimoNome){
        DesafioWebjumpElements.campoUltimoNome().should('be.visible').type(ultimoNome);
    },
    insereEmailCadastro(email){
        DesafioWebjumpElements.campoEmailCadastro().should('be.visible').type(email);
    },
    insereSenhaCadastro(senha){
        DesafioWebjumpElements.campoSenhaCadastro().should('be.visible').type(senha);
    },
    confirmaSenha(senha){
        DesafioWebjumpElements.campoConfirmaSenha().should('be.visible').type(senha);
    },
    clicarNoBotaoEfetuarCadastro(){
        DesafioWebjumpElements.botaoEfetuarCadastro().should('be.visible').click();
    },
    confirmaCadastro(){
        DesafioWebjumpElements.confirmarCadastro().should('be.visible');
    },
    insereEmailLogin(email){
        DesafioWebjumpElements.campoEmailLogin().should('be.visible').type(email);
    },
    insereSenhaLogin(senha){
        DesafioWebjumpElements.campoSenhaLogin().should('be.visible').type(senha);
    },
    clicarNoBotaoLogar(){
        DesafioWebjumpElements.botaoLogar().should('be.visible').click();
    },
    confirmaLogin(){
        DesafioWebjumpElements.confirmaLogin().should('be.visible');
    },
    clicarNoMenuGear(){
        DesafioWebjumpElements.menuGear().should('be.visible').click();
    },
    clicarNoMenuBags(){
        DesafioWebjumpElements.menuBags().should('be.visible').click();
    },
    clicarNoProduto(){
        DesafioWebjumpElements.produto().should('be.visible').click();
    },
    clicarNoBotaoAdicionarAoCarrinho(){
        DesafioWebjumpElements.botaoAdicionarAoCarrinho().should('be.visible').click();
    },
    clicarNoCarrinho(){
        DesafioWebjumpElements.botaoCarrinho().should('be.visible').click();
    },
    confirmaAdicaoAoCarrinho(){
        DesafioWebjumpElements.confirmaAdicaoAoCarrinho().should('be.visible');
    },
    confirmaItemNoCarrinho(){
        DesafioWebjumpElements.confirmaItemNoCarrinho().should('be.visible');
    },
    clicarNoBotaoFinalizarCompra(){
        DesafioWebjumpElements.botaoFinalizarCompra().should('be.visible').click();
    }
}